//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SOClient.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MAINVIEW_FORM               101
#define IDR_MAINFRAME                   128
#define IDR_SOCLIETYPE                  129
#define IDB_MAIN_IMAGE                  129
#define IDR_DAWRITE                     129
#define IDI_ICON1                       130
#define IDB_OBJECT_IMAGE                130
#define IDI_ICON2                       131
#define IDR_OBJECT_POPUP                131
#define IDB_DAWRITEITEM_UP              131
#define IDR_OBJECT_EMPTY_POPUP          131
#define IDI_ICON3                       132
#define IDB_DAWRITEITEM_DISABLED        132
#define IDR_MAIN_POPUP                  132
#define IDB_DAWRITEITEM_FOCUS           133
#define IDR_MAIN_POPUP_TREE_DA          133
#define IDD_PROPERTY                    133
#define IDB_DAWRITEITEM_DOWN            134
#define IDD_PP_GROUP                    134
#define IDR_OBJECT_SERVERDA_POPUP       134
#define IDB_OK_N                        135
#define IDD_PP_ITEM_ATTRIBUTES          135
#define IDR_OBJECT_ITEM_POPUP           135
#define IDD_PP_ITEM_WRITE               136
#define IDR_PROPERTYFRAME               136
#define IDR_OBJECT_GROUP_POPUP          136
#define IDD_PP_SERVER_ATTRIBUTES        137
#define IDR_OBJECT_SERVERAE_POPUP       137
#define IDB_RESET_D                     138
#define IDD_PP_SERVER_STATUS            138
#define IDR_OBJECT_SUBSCRIPTION_POPUP   138
#define IDD_PP_SERVER_BROWSE            139
#define IDR_OBJECT_NODE_POPUP           139
#define IDD_PP_ABOUT                    140
#define IDR_OBJECT_TAG_POPUP            140
#define IDB_RESET_U                     141
#define IDD_PP_TAG_PROPERTY             141
#define IDD_PP_TAG                      141
#define IDR_OBJECT_PROPERTY_POPUP       141
#define IDD_PP_PROPERTY                 142
#define IDR_OBJECT_NAMESPACEBROWSER_POPUP 142
#define IDR_OBJECT_OPCSERVER_POPUP      143
#define IDD_PP_SERVERAE_STATUS          143
#define IDR_OBJECT_EVENTCOND_POPUP      144
#define IDD_PP_SERVERAE_BROWSE          144
#define IDD_PP_SERVERAE_ATTRIBUTES      145
#define IDD_PP_SUBSCRIPTION_ATTRIBUTES  146
#define IDB_OK_D                        150
#define IDB_OK_U                        153
#define IDB_RESET_N                     155
#define IDB_EDIT_D                      156
#define IDB_EDIT_U                      157
#define IDB_EDIT_N                      158
#define IDR_ERRORLST_POPUP              159
#define IDD_DLG_OPTIONS                 160
#define IDD_PP_TAG_WRITE                161
#define IDD_PP_SERVER_SECURITY          162
#define IDD_ABOUT                       171
#define IDR_HTML_DLGABOUT               172
#define IDD_MULTIWRITE                  174
#define IDC_LIST_TAB                    1000
#define IDC_LIST1                       1000
#define IDC_MAIN_LIST_DA                1000
#define IDC_TAB1                        1001
#define IDC_MAIN_TAB                    1001
#define IDC_MAIN_TREE_SRV               1002
#define IDC_MAIN_TREE_DA                1003
#define IDC_DAITEMVALUE                 1003
#define IDC_MAIN_TREE_AE                1004
#define IDC_DAITEMWRITE                 1004
#define IDC_MAIN_LIST_AE                1005
#define IDC_MAIN_LIST_ERR               1006
#define IDC_SERVER_PROGID               1007
#define IDC_PROPERTY_ITEM_ID            1007
#define IDC_MAIN_LIST_AEC               1007
#define IDC_SERVER_DESCR                1008
#define IDC_SERVER_CLSID                1009
#define IDC_SERVER_NODE                 1010
#define IDC_SERVER_VALID_CLIENT_NAME    1011
#define IDC_SERVER_CLIENT_NAME          1012
#define IDC_SERVER_VALID_LOCALE_ID      1013
#define IDC_SERVER_LOCALE_ID            1014
#define IDC_SERVER_OPC_VERSION          1015
#define IDC_SERVER_START_TIME           1016
#define IDC_SERVERAE_AVAILABLE_FILTERS  1016
#define IDC_SERVER_CURRENT_TIME         1017
#define IDC_SUBSCRIPTION_BUFFER_TIME    1017
#define IDC_SERVER_UPDATE_TIME          1018
#define IDC_SUBSCRIPTION_MAX_SIZE       1018
#define IDC_SERVER_STATE                1019
#define IDC_SUBSCRIPTION_CLIENT_HANDLE  1019
#define IDC_SERVER_GROUP_COUNT          1020
#define IDC_DA2_FILTER                  1020
#define IDC_SERVER_STATUS_INFO          1020
#define IDC_SERVER_BANDWIDTH            1021
#define IDC_DA3_FILTER                  1021
#define IDC_SERVER_VERSION              1022
#define IDC_SERVER_VENDOR_INFO          1023
#define IDC_TAG_WRITE_VALUE             1023
#define IDC_GROUP_NAME                  1024
#define IDC_GROUP_CONNECTION_TYPE       1025
#define IDC_GROUP_DATA_RETRIEVAL        1026
#define IDC_TAG_READ_VALUE              1026
#define IDC_GROUP_VALID_UPDATE_RATE     1027
#define IDC_GROUP_UPDATE_RATE           1028
#define IDC_TAG_READ_QUALITY            1028
#define IDC_GROUP_VALID_TIME_BIAS       1029
#define IDC_TAG_READ_TIMESTAMP          1029
#define IDC_GROUP_TIME_BIAS             1030
#define IDC_SERVER_USER_NAME            1030
#define IDC_GROUP_VALID_DEADBAND        1031
#define IDC_SERVER_PASSWORD             1031
#define IDC_GROUP_DEADBAND              1032
#define IDC_SERVER_STORE_SEC_INFO       1032
#define IDC_GROUP_VALID_LOCALE_ID       1033
#define IDC_LABEL_URL                   1033
#define IDC_GROUP_LOCALE_ID             1034
#define IDC_EDIT_URL                    1034
#define IDC_GROUP_SERVER_HANDLE         1035
#define IDC_BUTTON_ADDSERVER            1035
#define IDC_GROUP_CLIENT_HANDLE         1036
#define IDC_SERVER_USE_OPC_VERSION      1036
#define IDC_ITEM_ID                     1037
#define IDC_GROUP_VALID_UPDATE_RATE2    1037
#define IDC_GROUP_VALID_KEEP_ALIVE_TIME 1037
#define IDC_SERVER_URL                  1037
#define IDC_ITEM_DATATYPE               1038
#define IDC_GROUP_KEEP_ALIVE_TIME       1038
#define IDC_OPT_TIME_DATE               1038
#define IDC_ITEM_ACCESS_PATH            1039
#define IDC_ITEM_ACCESS_PATH_LIST       1040
#define IDC_TAG_NATIVE_DATATYPE         1041
#define IDC_TAG_ACCESS_RIGHTS           1042
#define IDC_TAG_EU_TYPE                 1043
#define IDC_TAG_EU_INFO                 1044
#define IDC_PERSISTENT                  1045
#define IDC_ITEM_VALID_DEADBAND         1045
#define IDC_ITEM_SERVER_HANDLE          1046
#define IDC_ITEM_CLIENT_HANDLE          1047
#define IDC_ITEM_WRITE_VALUE            1048
#define IDC_ITEM_DEADBAND               1048
#define IDC_ITEM_WRITE_START_IDX        1049
#define IDC_ITEM_WRITE_START_IDX_SPIN   1050
#define IDC_ITEM_WRITE_ARRAY            1051
#define IDC_ITEM_WRITE_DATATYPE         1052
#define IDC_OK                          1053
#define IDC_RESET                       1054
#define IDC_EDIT                        1055
#define IDC_PUBLIC                      1056
#define IDC_ITEM_BROWSE_TREE            1057
#define IDC_ITEM_BROWSE_LIST            1058
#define IDC_ITEM_ACCESS_RIGHTS          1059
#define IDC_ITEM_FILTER                 1060
#define IDC_ABOUT_LABEL_CV              1061
#define IDC_VENDOR_FILTER               1061
#define IDC_ABOUT_LABEL_BO              1062
#define IDC_ABOUT_VERSION               1063
#define IDC_ABOUT_BUILD_OPT             1064
#define IDC_ABOUT_LABEL_COPYRIGHT       1065
#define IDC_ABOUT_COMPILER_VERSION      1066
#define IDC_ABOUT_LABEL_COMPV           1067
#define IDC_OPT_TIME_LOCAL              1067
#define IDC_OPT_TIME_ONLY               1067
#define IDC_PROPERTY_LIST               1068
#define IDC_OPT_TIME_GMT                1068
#define IDC_PATH                        1069
#define IDC_OPT_CM_ON                   1069
#define IDC_PROPID                      1070
#define IDC_PROPERTY_PROP_ID            1070
#define IDC_OPT_CM_OFF                  1070
#define IDC_VALUE                       1071
#define IDC_PROPERTY_VALUE              1071
#define IDC_OPT_VALUE_PURE              1071
#define IDC_DATATYPE                    1072
#define IDC_PROPERTY_DATATYPE           1072
#define IDC_OPT_VALUE_VT                1072
#define IDC_DESCRIPTION                 1073
#define IDC_PROPERTY_DESCRIPTION        1073
#define IDC_OPT_IO_ERRORS_ON            1073
#define IDC_OPT_IO_ERRORS_OFF           1074
#define IDC_PROPERTY_PROP_NAME          1074
#define IDC_OPT_TRC_ON                  1075
#define IDC_OPT_TRC_OFF                 1076
#define IDC_OPT_VALUE_DEC               1077
#define IDC_OPT_VALUE_HEX               1078
#define IDC_OPT_ALPHAITEM_ON            1079
#define IDC_OPT_ALPHAITEM_OFF           1080
#define IDC_OPT_ALPHAAE_ON              1081
#define IDC_OPT_ALPHAAE_OFF             1082
#define ID_DELETEOBJECT                 32771
#define ID_VIEW_DAWRITE_BAR             32773
#define ID_GROUPUPDATERATE_FAST         32775
#define ID_GROUPUPDATERATE_STANDARD     32776
#define ID_GROUPUPDATERATE_SLOW         32777
#define ID_GROUPUPDATERATE_MEDIUM       32778
#define ID_ADDOBJECT                    32779
#define ID_ADDTAGSOFNODE                32780
#define ID_WRITEFROMFILE                32781
#define ID_READTOFILE                   32782
#define ID_EDIT_PROPERTIES              32784
#define ID_VIEW_PROPERTYVIEW            32785
#define ID_PROPERTY_APPLY               32790
#define ID_PROPERTY_RESET               32791
#define ID_SESSION_STOP                 32798
#define ID_SESSION_CONNECT              32799
#define ID_SESSION_START                32800
#define ID_PROPERTY_OK                  32803
#define ID_EDIT_ADDGROUP                32805
#define IDC_STOP                        32808
#define ID_EDIT_ADDSUBSCRIPTION         32816
#define ID_EDIT_ADDITEM                 32817
#define ID_START_DEEP                   32818
#define ID_START_FLAT                   32819
#define ID_CONNECT_DEEP                 32820
#define ID_CONNECT_FLAT                 32821
#define ID_STOP                         32822
#define ID_ITEM_READ                    32824
#define ID_GROUP_REFRESH                32825
#define ID_EDIT_ADDSERVER               32826
#define ID_EVENT_ACK                    32827
#define ID_VIEW_REFRESH                 32828
#define ID_ERROR_DELETEALL              32829
#define ID_EDIT_OPTIONS                 32830
#define ID_HELP_ABOUT                   32831
#define ID_ITEM_WRITE                   32832
#define ID_BROWSEALLTAGSOFNODE2FILE     32833
#define ID_LOGTOFILE                    32834
#define ID_ADDNEWGROUPWITHALLTAGS       32835

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
