#define BUILD_NUMBER 3920
#define BUILD_NUMBER_STR "3920"
#define MAJOR_VERSION_NUMBER 4
#define MINOR_VERSION_NUMBER 47
#define PATCH_VERSION_NUMBER 1
#define VERSION_TEXT "4.47.1"
#define UPDATE_INDEPENDENT_VERSION_STR "4.4x"

