//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

namespace DemoClient.Helper
{    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.softing.com/OPCToolboxClient")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.softing.com/OPCToolboxClient", IsNullable = false)]
    public partial class OPCToolboxClient
    {

        private OPCToolboxClientSessions sessionsField;

        /// <remarks/>
        public OPCToolboxClientSessions Sessions
        {
            get
            {
                return this.sessionsField;
            }
            set
            {
                this.sessionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.softing.com/OPCToolboxClient")]
    public partial class OPCToolboxClientSessions
    {

        private  List<OPCToolboxClientSessionsDASession> dASessionField;

        private List<OPCToolboxClientSessionsAESession> aESessionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DASession")]
        public List<OPCToolboxClientSessionsDASession> DASession
        {
            get
            {
                return this.dASessionField;
            }
            set
            {
                this.dASessionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AESession")]
        public List<OPCToolboxClientSessionsAESession> AESession
        {
            get
            {
                return this.aESessionField;
            }
            set
            {
                this.aESessionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.softing.com/OPCToolboxClient")]
    public partial class OPCToolboxClientSessionsDASession
    {

        private List<OPCToolboxClientSessionsDASessionDASubscription> subscriptionsField;

        private string urlField;

        private string localeIdField;

        private string clientNameField;

        private string dcomClsctxField;

        private OPCToolboxClientSessionsDASessionForcedOpcVersion forcedOpcVersionField;

        private bool forcedOpcVersionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DASubscription", IsNullable = false)]
        public List<OPCToolboxClientSessionsDASessionDASubscription> Subscriptions
        {
            get
            {
                return this.subscriptionsField;
            }
            set
            {
                this.subscriptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocaleId
        {
            get
            {
                return this.localeIdField;
            }
            set
            {
                this.localeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DcomClsctx
        {
            get
            {
                return this.dcomClsctxField;
            }
            set
            {
                this.dcomClsctxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OPCToolboxClientSessionsDASessionForcedOpcVersion ForcedOpcVersion
        {
            get
            {
                return this.forcedOpcVersionField;
            }
            set
            {
                this.forcedOpcVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForcedOpcVersionSpecified
        {
            get
            {
                return this.forcedOpcVersionFieldSpecified;
            }
            set
            {
                this.forcedOpcVersionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.softing.com/OPCToolboxClient")]
    public partial class OPCToolboxClientSessionsDASessionDASubscription
    {

        private List<OPCToolboxClientSessionsDASessionDASubscriptionDAItem> itemsField;

        private double updateRateField;

        private string nameField;

        private uint keepAliveTimeField;

        private bool keepAliveTimeFieldSpecified;

        private double deadbandField;

        private bool deadbandFieldSpecified;

        private string localeIdField;

        private bool activeField;

        public OPCToolboxClientSessionsDASessionDASubscription()
        {
            this.activeField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DAItem", IsNullable = false)]
        public List<OPCToolboxClientSessionsDASessionDASubscriptionDAItem> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double UpdateRate
        {
            get
            {
                return this.updateRateField;
            }
            set
            {
                this.updateRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint KeepAliveTime
        {
            get
            {
                return this.keepAliveTimeField;
            }
            set
            {
                this.keepAliveTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeepAliveTimeSpecified
        {
            get
            {
                return this.keepAliveTimeFieldSpecified;
            }
            set
            {
                this.keepAliveTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Deadband
        {
            get
            {
                return this.deadbandField;
            }
            set
            {
                this.deadbandField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeadbandSpecified
        {
            get
            {
                return this.deadbandFieldSpecified;
            }
            set
            {
                this.deadbandFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocaleId
        {
            get
            {
                return this.localeIdField;
            }
            set
            {
                this.localeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.softing.com/OPCToolboxClient")]
    public partial class OPCToolboxClientSessionsDASessionDASubscriptionDAItem
    {

        private string itemIdField;

        private string itemPathField;

        private string requestedDatatypeField;

        private double deadbandField;

        private bool deadbandFieldSpecified;

        private bool activeField;

        public OPCToolboxClientSessionsDASessionDASubscriptionDAItem()
        {
            this.activeField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemId
        {
            get
            {
                return this.itemIdField;
            }
            set
            {
                this.itemIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemPath
        {
            get
            {
                return this.itemPathField;
            }
            set
            {
                this.itemPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequestedDatatype
        {
            get
            {
                return this.requestedDatatypeField;
            }
            set
            {
                this.requestedDatatypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Deadband
        {
            get
            {
                return this.deadbandField;
            }
            set
            {
                this.deadbandField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeadbandSpecified
        {
            get
            {
                return this.deadbandFieldSpecified;
            }
            set
            {
                this.deadbandFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.softing.com/OPCToolboxClient")]
    public enum OPCToolboxClientSessionsDASessionForcedOpcVersion
    {

        /// <remarks/>
        DEFAULT,

        /// <remarks/>
        DA10,

        /// <remarks/>
        DA20,

        /// <remarks/>
        DA30,

        /// <remarks/>
        AE10,

        /// <remarks/>
        XMLDA10,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.softing.com/OPCToolboxClient")]
    public partial class OPCToolboxClientSessionsAESession
    {

        private List<OPCToolboxClientSessionsAESessionAESubscription> subscriptionsField;

        private string urlField;

        private string localeIdField;

        private string clientNameField;

        private string dcomClsctxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AESubscription", IsNullable = false)]
        public List<OPCToolboxClientSessionsAESessionAESubscription> Subscriptions
        {
            get
            {
                return this.subscriptionsField;
            }
            set
            {
                this.subscriptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocaleId
        {
            get
            {
                return this.localeIdField;
            }
            set
            {
                this.localeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DcomClsctx
        {
            get
            {
                return this.dcomClsctxField;
            }
            set
            {
                this.dcomClsctxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.softing.com/OPCToolboxClient")]
    public partial class OPCToolboxClientSessionsAESessionAESubscription
    {

        private uint bufferTimeField;

        private uint maxSizeField;

        private bool activeField;

        public OPCToolboxClientSessionsAESessionAESubscription()
        {
            this.bufferTimeField = ((uint)(0));
            this.maxSizeField = ((uint)(0));
            this.activeField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint BufferTime
        {
            get
            {
                return this.bufferTimeField;
            }
            set
            {
                this.bufferTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint MaxSize
        {
            get
            {
                return this.maxSizeField;
            }
            set
            {
                this.maxSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
}
