package com.softing.opc.client.enums;

import com.softing.opc.client.impl.jna.OTClient;

public enum EnumTraceGroup {

	ALL (OTClient.OT_TRACEMASK_ALL),
	NOTHING (OTClient.OT_TRACEMASK_NOTHING),
	USER (OTClient.OT_TRACEMASK_USER),
	OPCCLIENT (OTClient.OT_TRACEMASK_COPC),
	OPCCLIENTCALL (OTClient.OT_TRACEMASK_COPCCALL),
	OPCCLIENTADVISE (OTClient.OT_TRACEMASK_COPCADVISE),
	OPCSERVER (OTClient.OT_TRACEMASK_SOPC),
	OPCSERVERCALL (OTClient.OT_TRACEMASK_SOPCCALL),
	OPCSERVERADVISE (OTClient.OT_TRACEMASK_SOPCADVISE),
	CLIENT (OTClient.OT_TRACEMASK_TBCLIENT),
	SERVER (OTClient.OT_TRACEMASK_TBSERVER),
	LICENSE (OTClient.OT_TRACEMASK_OTBLICENSE),
	OTSIN (OTClient.OT_TRACEMASK_OTSIN),
	OTSOUT (OTClient.OT_TRACEMASK_OTSOUT),
	OTCIN (OTClient.OT_TRACEMASK_OTCIN),
	OTCOUT (OTClient.OT_TRACEMASK_OTCOUT),
	USER1 (OTClient.OT_TRACEMASK_USER1),
	USER2 (OTClient.OT_TRACEMASK_USER2),
	USER3 (OTClient.OT_TRACEMASK_USER3),
	USER4 (OTClient.OT_TRACEMASK_USER4),
	USER5 (OTClient.OT_TRACEMASK_USER5),
	USER6 (OTClient.OT_TRACEMASK_USER6),
	USER7 (OTClient.OT_TRACEMASK_USER7),
	USER8 (OTClient.OT_TRACEMASK_USER8);
	
	private final long traceGroup;
	
	EnumTraceGroup(long value)
	{
		traceGroup = (int)value;
	}
	
	public long toLong()
	{
		return traceGroup;
	}
	
}
